name: Build Theos Tweak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # Используем macOS, так как Xcode доступен только на ней.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Скачиваем ваш код из репозитория

    - name: Install Theos Dependencies
      run: |
        # Установка зависимостей Homebrew, необходимых для Theos
        brew install dpkg xz coreutils rsync openssh git
        # Устанавливаем 'ldid' - необходим для подписи dylib Theos'ом
        brew install ldid

    - name: Clone and Setup Theos
      run: |
        # Клонируем Theos в домашний каталог пользователя (~/theos).
        # Это гарантирует, что у пользователя есть права на запись.
        git clone --recursive https://github.com/theos/theos.git ~/theos
        
        # Устанавливаем переменные окружения для Theos в этом рабочем процессе
        echo "THEOS=~/theos" >> $GITHUB_ENV
        echo "$HOME/theos/bin" >> $GITHUB_PATH

    - name: Configure Theos Environment Variables
      run: |
        # Устанавливаем путь к SDK iOS, который Theos использует для компиляции
        echo "THEOS_SDK_PATH=$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk" >> $GITHUB_ENV
        # Примечание: Переменные вроде THEOS_DEVICE_IP не нужны для просто сборки .dylib.

    - name: Verify Project Files Presence
      run: |
        # Проверяем, что main.mm существует в корне репозитория
        if [ ! -f "main.mm" ]; then
          echo "Error: main.mm not found in the repository root. Please ensure it's there."
          exit 1
        fi
        # Проверяем, что libdobby.a существует по указанному пути
        if [ ! -f "dobby/universal/libdobby.a" ]; then
          echo "Error: dobby/universal/libdobby.a not found. Please ensure it's in your repository."
          exit 1
        fi
      working-directory: ${{ github.workspace }}

    - name: Build Tweak (dylib only)
      run: |
        # Выполняем команду 'make' для сборки вашего твика.
        # Theos скомпилирует исходники и создаст .dylib файл
        make
      working-directory: ${{ github.workspace }} # Убедитесь, что команда 'make' выполняется в корне вашего репозитория

    - name: List Theos Output Directory
      run: |
        # Выводим содержимое директории, куда Theos должен был поместить dylib.
        # Это поможет нам точно определить, где находится файл.
        echo "Listing contents of .theos/obj/:"
        ls -laR .theos/obj/ || true # Использование || true предотвратит падение шага, если директория пуста
      working-directory: ${{ github.workspace }}

    - name: Find and Upload dylib Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DobbyIphoneTweak-dylib # Имя артефакта, которое вы сможете скачать
        path: |
          .theos/obj/*.dylib # Попробуем более общий шаблон
          .theos/obj/debug/*.dylib # Если он в debug папке
          .theos/obj/release/*.dylib # Если он в release папке
        if-no-files-found: error # Завершаем с ошибкой, если .dylib не найден