name: Build Theos Tweak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # Используем macOS, так как Xcode доступен только на ней.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Скачиваем ваш код из репозитория

    - name: Install Theos
      run: |
        # Установка зависимостей, необходимых для Theos
        brew install dpkg xz lzma coreutils rsync openssh git
        
        # Скачиваем Theos
        git clone --recursive https://github.com/theos/theos.git /usr/local/theos
        echo "THEOS=/usr/local/theos" >> $GITHUB_ENV
        echo "/usr/local/theos/bin" >> $GITHUB_PATH

    - name: Configure Theos Environment Variables
      run: |
        # Важные переменные для Theos
        echo "THEOS_SDK_PATH=$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk" >> $GITHUB_ENV
        # Можно добавить дополнительные переменные, если они нужны вашему makefile

    - name: Prepare Dobby Library
      run: |
        # Проверяем, что libdobby.a существует по указанному пути
        if [ ! -f "dobby/universal/libdobby.a" ]; then
          echo "Error: dobby/universal/libdobby.a not found. Please ensure it's in your repository."
          exit 1
        fi
      working-directory: ${{ github.workspace }}

    - name: Build Tweak (dylib only)
      run: |
        # Для сборки только .dylib файла, достаточно просто выполнить make
        # Theos автоматически создаст .dylib в директории .theos/obj/debug/ (или release)
        make
      working-directory: ${{ github.workspace }} # Убедитесь, что команда make выполняется в корне вашего репозитория

    - name: Find and Upload dylib Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DobbyIphoneTweak-dylib # Имя артефакта, используем ваше TWEAK_NAME
        path: |
          .theos/obj/debug/DobbyIphoneTweak.dylib
          .theos/obj/release/DobbyIphoneTweak.dylib
        if-no-files-found: error # Выдавать ошибку, если dylib не найден