name: Build iOS Dylib with Dobby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # Используем последний доступный macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode 15.4
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4' # Указываем конкретную версию Xcode. Попробуй '15.4' или 'latest-stable'

    - name: Configure CMake
      run: |
        # После setup-xcode, xcode-select -p должен указывать на выбранную версию Xcode
        # И путь к iOS.cmake будет стандартным.
        cmake -S . -B build \
              -DCMAKE_TOOLCHAIN_FILE=$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/share/cmake/Modules/Platform/iOS.cmake \
              -G "Xcode"

    - name: Build project
      run: |
        cmake --build build --config Release

    - name: Find and upload dylib
      uses: actions/upload-artifact@v4
      with:
        name: YourProjectDylib
        path: build/Release/libYourProjectDylib.dylib
        retention-days: 7